### ISSUE TITLE
Can't create cookies when using SameSite=None in older versions of Chrome.

### ISSUE THREAD

**Issue by meghna-gupta** [GoogleChromeLabs/samesite-examples#2]
Hi @rowan-m ,
I'm using Chrome v62. I transformed my cookie attributes as below:

```js
document.cookie = cname + "=" + cvalue
  + "; " + "expires=" + d.toUTCString()
  + "; path=/; sameSite=None; secure;";  
// where cname = cookie name,
// cvalue = cookie value,
// and d = expiry date epoch
```

As mentioned in the documentation of this feature, I was expecting the default behaviour of cookie being created but None attribute value not recognised. But, the cookie is not getting created  altogether.
Can you please explain why?

P.S:
When i ran the same code with Chrome v76, the code is running fine. Cookie gets created as well as it recognises the None attribute and the secure flag.

**Comment by rowan-m** [comment]
Hey there, it looks like the issue you are hitting is that for Chrome 62 (which I believe was released some time in 2017) appears to be implementing the correct behaviour for the spec **at that time**.

https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-02#section-4.1.2.7
> August 7, 2017
> If the "SameSite" attribute's value is neither of these, the cookie will be ignored.

https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-03#section-4.1.2.7
> April 27, 2019
> If the "SameSite" attribute's value is something other than these three known keywords, the attribute's value will be treated as "None".

I'm interested to know what the scenario is that means you're dealing with an old version. Is there a reason the browser cannot be updated?

**Comment by meghna-gupta** [comment]
@rowan-m  Thanks for replying!
I got that 'None' is not being recognised by older versions of Chrome, as mentioned in the documentation. But is there any way so that I can implement 'None' for 'SameSite' and still get the cookie running for older versions?

My scenario is that I'm updating my cookie attributes (according to the [recent recommendations by Google Chrome](https://blog.chromium.org/2019/05/improving-privacy-and-security-on-web.html)) on production level. I'm interested to know the cookie behaviour with different browsers and versions.

**Comment by rowan-m** [comment]
I'm in the process of updating our guidance on web.dev, but I have an early preview here:
https://deploy-preview-1367--web-dev-staging.netlify.com/samesite-cookies-explained/#handling-incompatible-clients

Essentially, you can either:
- sniff the user agent for clients known to be incompatible and serve a cookie without the `SameSite` attribute for those browsers
- set two versions of the cookie - one with `SameSite` and one without, then check the new version first and the legacy version second

My preference is for setting two cookies as while that's a bit heavier in the request / response, it should work for every client regardless of proper UA detection.

**Comment by meghna-gupta** [comment]
@rowan-m 
As I have many cookies working, I think I'll have to go with the first approach.

Thanks for the help!

**Comment by meghna-gupta** [comment]
Will my cookies serve in third-party context if I don't use **SameSite**, after Chrome 80 release?

**Comment by rowan-m** [comment]
No. You should assume that from Chrome 80 onwards, if you want cookies sent in a third party context then you **must** define them as `SameSite=None; Secure`. If you serve a cookie without these attributes, it will be treated as if it was the more restrictive `SameSite=Lax`.

**Comment by panva** [comment]
@rowan-m ad your early preview draft

```
    if (
      // iOS 12 browsers
      (ua.os.name == 'iOS' && ua.os.version.startsWith('12')) ||
      // or MacOS 10.14
      (ua.os.name == 'Mac OS' && ua.os.version.startsWith('10.14'))
    ) {
```

Is this comprehensive? I think the iOS ua.os.version major should be parsed as int and checked to be lte 12. Also, isn't us.os.name == 'Mac OS' also going to target Chrome for macOS? Dtto for versions parsing.

I think the example here needs to be as bulletproof as possible because developers are going to take it verbatim and put in their codebases.

It is really a bummer that we as developers are forced upon these changes and are given no comprehensive guidance. It feels like everyone's out for themselves.

**Comment by rowan-m** [comment]
Hey @panva I'm just in the process of updating that article. Specifically, I'm revising the advice there as after more investigation I think **UA sniffing is too fragile** and I would not recommend it. Instead, I would advise using the double cookie approach to provide a path for browsers that don't yet implement the latest version of the RFC.

So, specifically:
* Request - Set both new and legacy style cookies:
```
Set-cookie: ck_name=value; SameSite=None; Secure;
Set-cookie: ck_name-legacy=value;
```
* Response - Check new style, fall back to legacy:
```
if (cookies[´ck_name´]) {
  ckVar = cookies[´ck_name´]
} else if (cookies[´ck_name-legacy´]) {
  ckVar = cookies[´ck_name-legacy´]
}
```

I appreciate that it is a trade-off and increases the cookie payload, but this should ensure that you can serve all clients without needing to detect capabilities.

**Comment by kanadaj** [comment]
@rowan-m This seems to be causing headaches across the board; it is implied that double cookies could cause issues with cookie limits, see the conversation at https://github.com/aspnet/AspNetCore/issues/14996#issuecomment-541935157

**Comment by slaneyrw** [comment]
OpenId/Connect, WSFederation, and SAML SSO implementations are potentially affected by this as well.

**Comment by rowan-m** [comment]
Closing this as I've merged in the PR from the .NET team. @slaneyrw I'll take a look at the identity providers, but are you already aware of specific issues they have?
