### ISSUE TITLE
What to do if your service needs SameSite=None, Secure and you need to support Safari

### ISSUE THREAD

**Issue by istarkov** [GoogleChromeLabs/samesite-examples#3]
In our case Safari users are > 50% of all logins
And we use services like auth etc on standalone domain,
what the recommended way to not broke Safari users and Chrome?

Even Safari will fix the issue on upcoming Safari version, there will be a lot of users on IOS12-10 etc.

**Comment by panva** [comment]
set two cookies, with and without samesite, see https://github.com/GoogleChromeLabs/samesite-examples/issues/2#issuecomment-535195768

**Comment by istarkov** [comment]
Ok Thank you, thought the same.
