### ISSUE TITLE
There are foos and bars without any sort of definition whatsoever.

### ISSUE THREAD

**Issue by 619** [GoogleChromeLabs/samesite-examples#37]
In your nodeJS example, you call response.cookie with the parameters 'foo' and 'bar'. 

???

**Comment by rowan-m** [comment]
Fair point, I'll update the cookie names and values to be a bit more informative. The `foo` is just the cookie name and `bar` is just the value.

**Comment by 619** [comment]
Thanks Rowan, much appreciated!
