### ISSUE TITLE
Samesite cookie issue

### ISSUE THREAD

**Issue by AswaniRenjith** [GoogleChromeLabs/samesite-examples#46]
We are interacting with a payment gateway in our web application.
Due to the latest update in chrome we are unable to get the session cookie as response after successful payment.
Could you please guide us to find whether the samesite cookie attribute needs to be updated from our end or should the payment gateway needs to make the changes.

**Comment by AswaniRenjith** [comment]
@rowan-m   Could you please guide us to find the solution

**Comment by rowan-m** [comment]
This sounds as if you might be hitting something similar to: https://github.com/GoogleChromeLabs/samesite-examples/blob/3d-secure-impl/3d-secure.md

**Comment by AswaniRenjith** [comment]
@rowan-m Thank you so much :)
