### ISSUE TITLE
Confused by docs: cross-site image request with credentials

### ISSUE THREAD

**Issue by mok419** [GoogleChromeLabs/samesite-examples#53]
Quick summary: I have two domains. A returns sameSite=None Secure cookie on login, which grants access to /img. B has an img tag that tries to load the image from A. But cookies are not being sent from B to A!

Hi I've watched @hnasr video on [sameSite cookies ](https://www.youtube.com/watch?v=aUF2QCEudPo) and I've been playing around today but I am more confused than confident in how cross site cookies work!

I am trying to achieve exactly what Hussein achieved in the video - he set the cookie from domainA as sameSite=none; secure and then the img would load on domainB with no issues, sending the cookies to gain access.

I don't understand how he has achieved this. 

My domain A is [https://express-cross-site-cookie.onrender.com](https://express-cross-site-cookie.onrender.com) - the same express server Hussein used!
My domain B is [https://mok419.github.io](https://mok419.github.io) - I can't seem to load the image from domain A here!!

My main issue is that when I use a normal img tag with only src=https://express-cross-site-cookie.onrender.com  no cookies are sent. Then I tried adding crossOrigin="allowCredentials" and now I get back a CORs error. 

Hussein didn't use any CORs on the server, so why is my browser expecting CORs setup. Has this been patched or something as I can't find much about anyone trying to load an image which relies on cookies. I read that it could be a Cloudflare cache issue, but bypassing cache with a URL parameter doesn't help!

Many thanks!!

Repo for domain A https://github.com/mok419/cross-site-cookies
Repo for domain B https://github.com/mok419/mok419.github.io

**Comment by hnasr** [comment]
google has started deprecating Third party cookies (samesite=none essentially) .You might be among the 1% experiment. that might explain why it's working anymore. I wrote about this here and left resources too. 

https://medium.com/@hnasr/google-is-deprecating-3rd-party-cookies-d987603607a7

**Comment by mok419** [comment]
Legend! Thanks a lot for confirming!

It makes sense as I remember tracking cookies being banned a while back! This definitely makes it harder for trackers which is a huge positive for privacy & security!

Anyone from the future, here is another good read on the topic! (why I am the 1% to experience this!!)
https://www.invoca.com/en-gb/blog/tracking-cookies-are-dead-what-marketers-can-do-about-it
