### ISSUE TITLE
how can i implement SetSite=none in Java

### ISSUE THREAD

**Issue by waseemmubasher93** [GoogleChromeLabs/samesite-examples#8]
i am looking to the Cookie API there is no setter for 'SetSite' also Tomcat 9.0.30 supports it but some of my application doesn't run on tomcat they on another servers. so i can resolve it in java.
i just found this example but i dont wanna do in this way

response.setHeader("Set-Cookie", "key=value; SameSite=none; Secure")

**Comment by saybee** [comment]
Even I am looking for implementation for SameSite=none in Java.

**Comment by waseemmubasher93** [comment]
the first solution for SameSite=none in java is if you are using Tomcat server so just put
`<CookieProcessor className="org.apache.tomcat.util.http.LegacyCookieProcessor" sameSiteCookies="none" />` 
in your tomcat context.xml and for each cookies which you set in response just add secure with that. so i tested in production its working. 
the another solution is implement own class if your server is not tomcat.

**Comment by saybee** [comment]
I am using a TomEE server.

**Comment by aditya-padhi-kbl** [comment]
@waseemmubasher93 how to add secure ? I think we have to add samesite none as well as secure ?
